### PR TITLE
Assignment6

### PR DESCRIPTION
**Pull request by Ashrom0**

### CODE REVIEW

**Comment by Ashrom0** [comment]
This is just the bare bone of this assignment, will continue to update soon

**Comment by TechGlue** [comment]
will review!

**Review by TechGlue — COMMENTED** [review]
## Assignment

- Configure a CI Build against the SecretSanta solution
  - Compile all the source code ✔
  - Run all the user tests ❌
  - Add the Build Status to the Read.me file of your project.  (Be sure to use relative links so it works across branches and even when forked.) ✔
  - Place a URL to your fork and branch in your readme (so that we can easily navigate there to see the build) ✔
- Configure a CD deployment of the project (https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions)✔
  - Configure an Azure Web App (using the Azure Portal) ✔
  - Configure a GitHub Action to deploy to an Azure Web App (https://github.com/Azure/webapps-deploy) ✔
  - Add the Deploy Status to the Read.me file of your project.  (Be sure to use relative links so it works across branches and even when forked.) ✔
  - Be sure to deploy the API project and verify that the UI that calls the API project works correctly. This will require you to update the URL/address in the Web project that points to the API project. ❌
- Place a hyperlink to the running website in both your Readme and your PR. (Consider using a badge that shows whether the site is up or not.) ✔

**Comment by TechGlue** [comment]
Looking good but you do need to run all test that is including the API tests. So just include the commands to run those In your assignment build and tests.yml file and you should be good.

**Comment by Ashrom0** [comment]
Fork/Branch : https://github.com/Ashrom0/EWU-CSCD379-2021-Spring/tree/Assignment6

Actions: https://github.com/Ashrom0/EWU-CSCD379-2021-Spring/actions

Website : https://ashrom-ewu379-2021-spring.azurewebsites.net

**Comment by mmwoodfo** [comment]
Good job 👍🏻

**Pull request closed without merging**
