### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thecactus1**

### CODE REVIEW

**Comment by NicholasJohnsonDev** [comment]
I'll review this.

**Comment by NicholasJohnsonDev** [comment]
Deploy Status is in the README but not functional as the workflow it references does not exist.
Build status not working either though the workflow is successful.
Current: Build
I would update it the name to match the job name and then update the status code to:


Assignment
Configure a CI Build against the SecretSanta solution
Compile all the source code ✔
Run all the user tests ✔
Add the Build Status to the Read.me file of your project. (Be sure to use relative links so it works across branches and even when forked.) ✔
Place a URL to your fork and branch in your readme (so that we can easily navigate there to see the build) ✔
Configure a CD deployment of the project (https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions)
Configure an Azure Web App (using the Azure Portal) ❌
Configure a GitHub Action to deploy to an Azure Web App (https://github.com/Azure/webapps-deploy) ❌
Add the Deploy Status to the Read.me file of your project. (Be sure to use relative links so it works across branches and even when forked.) ✔
Be sure to deploy the API project and verify that the UI that calls the API project works correctly. This will require you to update the URL/address in the Web project that points to the API project. ❌
Place a hyperlink to the running website in both your Readme and your PR. (Consider using a badge that shows whether the site is up or not.) ❌

Extra Credit
Have the Web Tests run against the deployed website after the deployment completes.
Configure the API site URL address into the Web Project during the deployment using a GitHub Action variable.
Configure code coverage and generate a report (see https://github.com/dotnet/docs/blob/main/docs/core/testing/unit-testing-code-coverage.md) ❌

**Comment by mmwoodfo** [comment]
Consider naming your PRs after the Assignment the PR is for. Also - you are missing a link to your deployed web app and your personal repo in your PR comment - I do see you put it in your readme though.

**Comment by mmwoodfo** [comment]
I cannot find a code review for you, did you do one?

**Comment by thecactus1** [comment]
I could have sworn I did. Any chance I can do it today?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mmwoodfo** [comment]
@thecactus1 I apologize for the late response. As far as I know, there is no way to make up a late code review since it is really meant as a way to give feedback to someone before their project is due. 

If you do end up finding the review please let us know by emailing EWUInstructors@IntelliTect.com or @ mentioning me or another instructor here so we can get your grade updated. It may exist - I just could not find it. I would suggest double-checking the PR you did the review one to see if it was submitted.

**Pull request closed without merging**
