### PR TITLE
Assignment-6

### PR DESCRIPTION
**Pull request by TechGlue**
Started on the assignment but am currently having issues with the SecretSanta.Api tests.  Work in progress.

### CODE REVIEW

**Comment by Ashrom0** [comment]
I will review this!

**Comment by TechGlue** [comment]
Currently having issues with the  SeceretSanta.API. But the website tests and deployment have been added to the .yml

**Review by Ashrom0 — COMMENTED** [review]
Configure a CI Build against the SecretSanta solution
- Compile all the source code ❌

- Run all the user tests ❌

- Add the Build Status to the Read.me file of your project. (Be sure to use relative links so it works across branches and even when forked.) ✔

Place a URL to your fork and branch in your readme (so that we can easily navigate there to see the build)
Configure a CD deployment of the project (https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions)
- Configure an Azure Web App (using the Azure Portal) ✔

- Configure a GitHub Action to deploy to an Azure Web App (https://github.com/Azure/webapps-deploy) ✔

- Add the Deploy Status to the Read.me file of your project. (Be sure to use relative links so it works across branches and even when forked.) ✔

-Be sure to deploy the API project and verify that the UI that calls the API project works correctly. This will require you to update the URL/address in the Web project that points to the API project. ❌

-Place a hyperlink to the running website in both your Readme and your PR. (Consider using a badge that shows whether the site is up or not.) ✔

**Comment by Ashrom0** [comment]
For the Xs I gave you, I see that your API Test in actions didnt compile, test, and not working properly. Other than that, the other things seems fine.

**Comment by TechGlue** [comment]
Assignment 6 completed here are there direct links to the branch and the actions page if needed. 
Branch - https://github.com/TechGlue/EWU-CSCD379-2021-Spring/tree/Assignment-6
Actions - https://github.com/TechGlue/EWU-CSCD379-2021-Spring/actions

**Comment by Ashrom0** [comment]
Don't forget to link the website.

**Comment by mmwoodfo** [comment]
Looks good, good job. You should have a link to the website in your PR comment - but I see you put it in your readme.

**Pull request closed without merging**
