### PR TITLE
Completed Assignment 4.

### PR DESCRIPTION
**Pull request by delta-plus**
This is Joe Grassl. In the nick of time, yo!

### CODE REVIEW

**Comment by cschadewitz** [comment]
Reviewing

**Comment by cschadewitz** [comment]
Everything looks good, except you did what I did and forgot to add a test project for the SecretSanta.Busines. 

I did get some odd behavior from the tests when running in the order they populated my Test Explorer, specifically Delete_WithId_ReturnsOk then Get_WithId_ReturnsUserManagerUser(1). This makes sense since they are affecting the same User. However based on the code, I am unsure as to why it occurs since you re-instantiate the UserManager on each test. 
    

Create a UserController in the API projects
        Implement endpoints for:
            Retrieving all users ✔
            Retriving a single user by id ✔
            Creating a user ✔
            Updating a user ✔
            Deleting a user ✔
        The UserController should function. ✔
        Include a .rest file for interacting with the controller (REST Client). ✔
    The IUserRepository interface is provided for you. You will need to provide an implementation of this interface within the SecretSanta.Business project. This implementation can simply store the user within a list, dictionary, array, or similar. ✔
    All test projects should be within a test directory ✔
    Create a unit test project for the SecretSanta.Business project. ❌
        Unit test all public methods ❌
        Ensure the project is named with a ".Tests" suffix ❌
        Ensure test class is named appropriately for the class being tested: ✔
        Name all tests in the form <MethodBeingTested>_<ConditionBeingTested>_<ExpectedOutcome>(). You can add <NoWarn>CA1707;INTL0003</NoWarn> to remove the naming warnings. ✔
    Create a Unit Test project for the SecretSanta.Api project. ✔
        Test all controller public methods. It is up to you to determine the best way to provide the controller's dependencies. ✔
        Ensure the project is named with a ".Tests" suffix ✔

Extra Credit:

    Use a test double library like Moq to provide the controller's dependencies.

**Comment by delta-plus** [comment]
I did include tests for SecretSanta.Business. You can look in the "Files Changed" tab. It's all there under test/SecretSanta.Business.Tests.

**Comment by cschadewitz** [comment]
Sorry about that, I did not see it when I opened the project as it appears to have not been added to the .sln file. I will add it and review. 
image

**Comment by delta-plus** [comment]
Thanks. Yeah, that was it. I forgot to add that one to the solution file.

**Review by Keboo — COMMENTED** [review]
Very nice work!
- Create a UserController in the API projects
  - Implement endpoints for:
    - Retrieving all users ✔
    - Retriving a single user by id ✔
    - Creating a user ✔
    - Updating a user ✔
    - Deleting a user ✔
  - The UserController should function. ✔
  - Include a `.rest` file for interacting with the controller. ✔
- The `IUserRepository` interface is provided for you. You will need to provide an implementation of this interface within the SecretSanta.Business project. This implementation can simply store the user within a list, dictionary, array, or similar. ✔
- All test projects should be within a test directory ✔
- Create a unit test project for the SecretSanta.Business project. ✔
  - Unit test all public methods ✔
  - Ensure the project is named with a ".Tests" suffix ✔
  - Ensure test class is named appropriately for the class being tested: ✔
  - Name all tests in the form `<MethodBeingTested>_<ConditionBeingTested>_<ExpectedOutcome>()`. You can add  `<NoWarn>CA1707;INTL0003</NoWarn>` to remove the naming warnings. ✔
- Create a Unit Test project for the SecretSanta.Api project. ✔
  - Test all controller public methods. It is up to you to determine the best way to provide the controller's dependencies. ✔
  - Ensure the project is named with a ".Tests" suffix ✔

**Pull request closed without merging**
