### PR TITLE
Assignment6

### PR DESCRIPTION
**Pull request by jamesgreiner**
Deployed initial Azure web app. Still need to update yml file, create/configure CI build and add status badges.

### CODE REVIEW

**Comment by jmplett** [comment]
I will review

**Comment by jmplett** [comment]
# Assignment 6

## Overview

In this project, we are going to configure continuous integration and continuous deployment.

## Assignment

- Configure a CI Build against the SecretSanta solution
  - Compile all the source code ❌
  - Run all the user tests ❌
  - Add the Build Status to the Read.me file of your project.  (Be sure to use relative links so it works across branches and even when forked.) ❌
  - Place a URL to your fork and branch in your readme (so that we can easily navigate there to see the build)
- Configure a CD deployment of the project (https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions)
  - Configure an Azure Web App (using the Azure Portal) ✔-- I cant tell since I cant view the cite but i think you did
  - Configure a GitHub Action to deploy to an Azure Web App (https://github.com/Azure/webapps-deploy) ❌ incomplete didn't pass
  - Add the Deploy Status to the Read.me file of your project.  (Be sure to use relative links so it works across branches and even when forked.) ❌
  - Be sure to deploy the API project and verify that the UI that calls the API project works correctly. This will require you to update the URL/address in the Web project that points to the API project. ❌
- Place a hyperlink to the running website in both your Readme and your PR. (Consider using a badge that shows whether the site is up or not.) ❌

## Extra Credit

- Have the Web Tests run against the deployed website after the deployment completes.
- Configure the API site URL address into the Web Project during the deployment using a GitHub Action variable.
- Configure code coverage and generate a report (see https://github.com/dotnet/docs/blob/main/docs/core/testing/unit-testing-code-coverage.md) ❌


I couldn't really tell if you configured everything with Azure correctly since I have not links to access it though it appears that you have started that step at least.

**Comment by jamesgreiner** [comment]
Assignment complete, links below:

[Link to website](https://ewu-spring-2021-secretsanta.azurewebsites.net/)
[Link to branch](https://github.com/jamesgreiner/EWU-CSCD379-2021-Spring/tree/Assignment6)

**Comment by mmwoodfo** [comment]
Looks good - good job.

**Pull request closed without merging**
