### PR TITLE
Completed Assignment 6.

### PR DESCRIPTION
**Pull request by delta-plus**
This is Joe Grassl.
My site: https://secretsantaserver.azurewebsites.net

### CODE REVIEW

**Comment by delta-plus** [comment]
Not sure what you're talking about but thanks for the check marks. The readme quite obviously does contain the Azure site URL and the Build and Deploy status badges. They're right at the top. Furthermore, there wasn't supposed to be a "link" to any .yml file. You find those under Actions in the branch. Finally, there most definitely is an Azure deploy file in my branch: Deploy.yml.

**Comment by delta-plus** [comment]
Ah, I see. You copy-pasted the review someone gave to your own code and just changed the Xs to checks on mine. No problemo, but you could be a bit more careful during your two-minute-long review next time. Scared me like that, man.

**Comment by ybaghlaf** [comment]
Wait, I thought they covered everything on mine?

**Comment by delta-plus** [comment]
Yeah, they covered everything in Xs. Sorry to see that. You still have until Tuesday night to fix things up, though, assuming their review is accurate.

**Comment by delta-plus** [comment]
You probably just didn't see the comments they had next to the Xs. I was just confused.

**Comment by delta-plus** [comment]
Yeah, that's much better. Thank you.

**Comment by ybaghlaf** [comment]
You're welcome.

**Comment by ybaghlaf** [comment]
Sorry for the confusion earlier, I reviewed it as soon as I woke up.

**Comment by delta-plus** [comment]
Understandable. It was an easy mistake to make. Thanks again for updating it.

**Comment by ybaghlaf** [comment]
No problem 😊

**Comment by mmwoodfo** [comment]
Great job.

**Pull request closed without merging**
